// AaClashQueryState
// PDB-CODE MODE
export const HANDLE_CODE_QUERY_INPUT = 'HANDLE_CODE_QUERY_INPUT';
export const ADD_PDB_CODE_QUERY = 'ADD_PDB_CODE_QUERY';
export const APPEND_PDB_CODE_QUERY_HISTORY = 'APPEND_PDB_CODE_QUERY_HISTORY';
export const DELETE_PDB_CODE_QUERY = 'DELETE_PDB_CODE_QUERY';
export const ERASE_PDB_CODE_QUERY_HISTORY = 'ERASE_PDB_CODE_QUERY_HISTORY';
// PDB-FILE MODE
export const HANDLE_FILE_QUERY_INPUT = 'HANDLE_FILE_QUERY_INPUT';
export const ADD_PDB_FILE_QUERY = 'ADD_PDB_FILE_QUERY';
export const APPEND_PDB_FILE_QUERY_HISTORY = 'APPEND_PDB_FILE_QUERY_HISTORY';
export const DELETE_PDB_FILE_QUERY = 'DELETE_PDB_FILE_QUERY';
export const ERASE_PDB_FILE_QUERY_HISTORY = 'ERASE_PDB_FILE_QUERY_HISTORY';
// GENERIC STATUS
export const LOADING_PDB_QUERY = 'PDB_QUERY_LOADING';
export const PDB_QUERY_FAILED = 'PDB_QUERY_FAILED';
export const SWITCH_AACLASH_QUERY_MODE = 'SWITCH_AACLASH_QUERY_MODE';
export const RESET_REDUX_APP_STATE = 'RESET_REDUX_APP_STATE'; 

// RCSB GraphQL component for info fetching
export const ADD_INDP_RCSB_PDB_ID_QUERY = 'ADD_INDP_RCSB_PDB_ID_QUERY';
export const DELETE_INDP_RCSB_ID_QUERY = 'DELETE_INDP_RCSB_ID_QUERY';
export const SELECT_RCSB_PDB_ID = 'SELECT_RCSB_PDB_ID';
export const SWITCH_RCSB_LIST_DISPLAY_MODE = 'SWITCH_RCSB_LIST_DISPLAY_MODE';
// MolComponent
export const SWITCH_MOL_LIST_DISPLAY_MODE = 'SWITCH_MOL_LIST_DISPLAY_MODE';
export const SWITCH_MOL_VIS_CHOICE = 'SWITCH_MOL_VIS_CHOICE';
export const ADD_INDP_MOL_PDB_ID_QUERY = 'ADD_INDP_MOL_PDB_ID_QUERY';
export const DEL_INDP_MOL_PDB_ID_QUERY = 'DEL_INDP_MOL_PDB_ID_QUERY';
// JSmol visualization
export const SET_JMOL_PDB_ID = 'SET_JMOL_PDB_ID';
export const SET_JMOL_AA_SUB_LIST = 'SET_JMOL_AA_SUB_LIST';
export const SET_JMOL_ZOOMED_IN_AA = 'SET_JMOL_ZOOMED_IN_AA';
export const IF_JMOL_WIREFRAME_ONLY = 'IF_WIREFRAME_ONLY';
export const IF_JMOL_DELAY_HOVER = 'IF_DELAY_HOVER';
// 3Dmol visualization
export const SET_3DMOL_PDB_ID = 'SET_3DMOL_PDB_ID';
export const SET_3DMOL_AA_POS = 'SET_3DMOL_AA_POS';
export const SET_3DMOL_ZOOMED_IN_AA = 'SET_3DMOL_ZOOMED_IN_AA';


