// AaClashQueryState
export const LOADING_PDB_QUERY = 'PDB_QUERY_LOADING';
export const ADD_PDB_CODE_QUERY = 'ADD_PDB_CODE_QUERY';
export const ADD_PDB_FILE_QUERY = 'ADD_PDB_FILE_QUERY';
export const APPEND_PDB_CODE_QUERY_HISTORY = 'APPEND_PDB_CODE_QUERY_HISTORY';
export const APPEND_PDB_FILE_QUERY_HISTORY = 'APPEND_PDB_FILE_QUERY_HISTORY';
export const PDB_QUERY_FAILED = 'PDB_QUERY_FAILED';
export const SWITCH_AACLASH_QUERY_MODE = 'SWITCH_AACLASH_QUERY_MODE';

// RCSB GraphQL component for info fetching
export const SWITCH_LIST_DISPLAY_MODE = 'SWITCH_LIST_DISPLAY_MODE';
export const SELECT_RCSB_PDB_ID = 'SELECT_RCSB_PDB_ID';

// JSmol visualization
export const SET_MOL_PDB_ID = 'SET_MOL_PDB_ID';
export const SET_MOL_AA_SUB = 'SET_MOL_AA_SUB';

